#!/usr/bin/env python

from json import loads
from string import join
from subprocess import Popen, PIPE

cmd = ["docker", "buildx"]
proc = Popen(cmd + ["bake", "--print"], stdout=PIPE)
data = loads(proc.stdout.read())

targets = data["target"]
platforms = []

for key in targets.keys():
    platforms.extend(targets[key]["platforms"])

proc = Popen(cmd + ["create", "--use", "--platform", join(set(platforms), ",")])
proc.wait()
proc = Popen(cmd + ["inspect"])
proc.wait()
